---

- name: Crear usuario y añadirlo a team viewnext
  hosts: localhost
  vars:
    username: usuario
    password: 1234
    email: usuario@example.com
    first_name: usuario
    last_name: usuario_last_name
    organization: organization1
    team: team1
    controller_host: http://1.1.1.1
    controller_username: admin
    controller_password: 1234
  tasks:
    - name: Crear usuario en organizacion
      awx.awx.user:
        username: "{{ username }}"
        password: "{{ password }}"
        email: "{{ email }}"
        first_name: "{{ first_name }}"
        last_name: "{{ last_name }}"
        organization: "{{ organization }}"
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        superuser: true
        validate_certs: false        
        state: present

    - name: Añadir usuario a team
      awx.awx.role:
        user: "{{ username }}"
        target_team: "{{ team }}"
        role: member
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false        
        state: present

...